/**
 * Created by WolfTungsten on 2018/2/16.
 */
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    body:{
        justifyContent:'center',
        alignItems:'stretch',
        height:'100%',
        backgroundColor:'#FFFFFF'
    },
    image:{
        width:81,
        height:81,
        alignSelf:'center'
    },
    signin:{
        justifyContent:'center',
        alignItems:'stretch',
        paddingLeft:27,
        paddingRight:27,
        flex:1
    },
    copyright:{
        alignSelf:'center',
        padding:25
    },
    title:{
        alignSelf:'center'
    },
    subTitle:{
        fontSize:14,
        color:'#A6A6A6',
        paddingTop:17
    },
    failMessage:{
        fontSize:14,
        color:'#EB5757',
        paddingTop:10,
        paddingBottom:10
    },
    button:{
        alignSelf:'flex-start',
    },
    accept:{
        flexDirection:'row',
        alignSelf:'center'
    },
    acceptText:{
        fontSize:12,
        padding:5,
        color:'#A6A6A6'
    }
})
